### ISSUE TITLE
Is the code of this repo related to QualDash?

### ISSUE THREAD

**Issue by 943fansi** [maya70/Qualdashv1#10]
Hi, @maya70 . I read the paper `QualDash: Adaptable Generation of Visualisation Dashboards for Healthcare Quality Improvement`,
and I am interested with this work. I searched the key word on GitHub, that's why I came here.

**Comment by maya70** [comment]
Hi, this is an older version of QualDash (may or may not work as the project hasn't been maintained for a while). Apologies for this.
